import type { Project } from "@/content/types";

export const nmsPlatformProject: Project = {
  slug: "nms-platform",
  title: "Network Monitoring Platform",
  year: "2026",
  role: "System Design, Backend, and Frontend Implementation",
  summary: "Distributed network monitoring platform for multi-site environments, using a local gateway agent, outbound MQTT delivery, ThingsBoard integration, and a custom operations dashboard.",
  stack: ["Go", "SQLite", "SNMP", "ICMP", "MQTT", "ThingsBoard", "PostgreSQL", "Next.js", "TypeScript", "Tailwind CSS"],
  featured: true,
  slides: [
    {
      number: 1,
      id: "overview",
      label: "Overview",
      title: "Network Monitoring Platform",
      layout: "title",
      eyebrow: "01 / 12",
      summary: "Distributed monitoring for multi-site network environments with local gateway collection and centralized visualization.",
      body: [
        "This project implements a monitoring architecture where each site runs a local gateway agent for collection and preprocessing, while ThingsBoard and a custom dashboard provide centralized visibility, alarms, and operational views.",
      ],
      metrics: [
        { label: "Collection", value: "Local gateway" },
        { label: "Transport", value: "Outbound MQTT" },
        { label: "Platform", value: "ThingsBoard" },
      ],
      image: {
        src: "/projects/nms-platform/dash-overview.png",
        alt: "NMS dashboard overview page",
        caption: "Dashboard overview showing centralized monitoring across the platform.",
      },
    },
    {
      number: 2,
      id: "problem",
      label: "Problem",
      title: "Problem",
      layout: "bullets",
      eyebrow: "02 / 12",
      image: {
        src: "/projects/nms-platform/problems.png",
        alt: "Problems",
        caption: "Centralized Monitoring",
      },
      bullets: [
        "Centralized SNMP polling across WAN links creates bandwidth overhead and scaling pressure on the monitoring server.",
        "Branch networks often sit behind NAT or firewall boundaries, making inbound polling from a central server less desirable.",
        "Raw interface counters require preprocessing before they become useful operational metrics such as throughput.",
        "A multi-site monitoring system needs centralized visibility without weakening local site isolation.",
      ],
    },
    {
      number: 3,
      id: "solution",
      label: "Solution",
      title: "Solution",
      layout: "split",
      eyebrow: "03 / 12",
      body: [
        "The solution moves collection and preprocessing to a local gateway at each site. The gateway polls devices locally through SNMP and ICMP, transforms raw data into ready-to-use telemetry, and sends it outbound to the central monitoring platform through MQTT.",
      ],
      aside: [
        "SNMP stays inside the local site network",
        "MQTT carries processed telemetry to the central platform",
        "ThingsBoard handles storage, rule processing, alarms, and visualization",
      ],
    },
    {
      number: 4,
      id: "architecture",
      label: "Architecture",
      title: "End-to-End Architecture",
      layout: "code",
      eyebrow: "04 / 12",
      body: [
        "The architecture separates local collection, central processing, and custom presentation. Site devices remain isolated while the central platform receives data through outbound communication.",
      ],
      image: {
        src: "/projects/nms-platform/end-to-end-architecture.png",
        alt: "End-to-end architecture diagram for the NMS platform",
        caption: "End-to-end system architecture from local site devices to centralized monitoring and dashboard presentation.",
      },
    },
    {
      number: 5,
      id: "agent",
      label: "Agent",
      title: "Agent Design",
      layout: "bullets",
      eyebrow: "05 / 12",
      bullets: [
        "Runs on the local gateway and polls devices inside the site network.",
        "Collects SNMP and ICMP telemetry without requiring the central server to reach internal devices directly.",
        "Preprocesses raw values, including interface counters, into operational metrics such as throughput and utilization.",
        "Keeps the core pipeline platform-agnostic through collector, processor, queue, and adapter boundaries.",
      ],
      image: {
        src: "/projects/nms-platform/nms-agent-design.png",
        alt: "NMS agent design diagram",
        caption: "Agent-side design showing collection, preprocessing, queuing, and delivery responsibilities.",
      },
    },
    {
      number: 6,
      id: "queue",
      label: "Reliability",
      title: "Queue and Reliability",
      layout: "metrics",
      eyebrow: "06 / 12",
      body: [
        "The gateway uses store-and-forward behavior so temporary connectivity issues between a site and the central server do not immediately discard telemetry.",
      ],
      metrics: [
        { label: "Local buffer", value: "SQLite queue" },
        { label: "Delivery model", value: "Retry + backoff" },
        { label: "Failure path", value: "Dead-letter" },
        { label: "Purpose", value: "WAN fault tolerance" },
      ],
    },
    {
      number: 7,
      id: "thingsboard",
      label: "Integration",
      title: "ThingsBoard Integration",
      layout: "bullets",
      eyebrow: "07 / 12",
      bullets: [
        "ThingsBoard acts as the central monitoring platform for telemetry ingestion, processing, storage, dashboarding, and alarms.",
        "MQTT provides lightweight publish-subscribe communication from local gateways to the central platform.",
        "Rule Engine logic supports site grouping, alarm generation, and entity processing based on incoming telemetry and attributes.",
        "PostgreSQL stores historical telemetry, attributes, and alarm records for later visualization and reporting.",
      ],
    },
    {
      number: 8,
      id: "bff",
      label: "BFF",
      title: "Backend for Frontend",
      layout: "bullets",
      eyebrow: "08 / 12",
      bullets: [
        "The Go BFF isolates frontend code from ThingsBoard authentication, API structure, and upstream response shape.",
        "It combines telemetry, attributes, alarms, reports, topology, and device data into dashboard-specific models.",
        "It preserves the rule that the frontend calls only the BFF, never ThingsBoard directly.",
        "It provides a cleaner contract for operational UI pages such as sites, devices, alarms, reports, and topology.",
      ],
    },
    {
      number: 9,
      id: "normalization",
      label: "Labels",
      title: "Readable Metrics",
      layout: "code",
      eyebrow: "09 / 12",
      code: "raw key:      snmp.if.idx2.rx_bps\nattribute:    snmp.if.idx2.name = eth0\nlabel output: eth0 RX Throughput",
      body: [
        "The dashboard converts technical telemetry keys into operator-readable labels by combining raw metric keys with device attributes. Raw telemetry keys remain unchanged internally.",
      ],
    },
    {
      number: 10,
      id: "dashboard",
      label: "UI",
      title: "Operations Dashboard",
      layout: "bullets",
      eyebrow: "10 / 12",
      bullets: [
        "Overview, sites, devices, alarms, reports, and topology are separated into operational pages.",
        "Device detail views include health cards, metric cards, charts, interfaces, storage, routing, alarms, and debug panels.",
        "Role-aware access follows ThingsBoard user authority, including tenant and customer scoped visibility.",
        "The UI focuses on readable labels and grouped metrics instead of exposing raw telemetry first.",
      ],
      gallery: [
        {
          src: "/projects/nms-platform/dash-site.png",
          alt: "NMS site dashboard page",
          caption: "Site-level view for grouped monitoring and operational status.",
        },
        {
          src: "/projects/nms-platform/dash-device.png",
          alt: "NMS device detail dashboard",
          caption: "Device detail dashboard with focused metrics and drill-down telemetry.",
        },
        {
          src: "/projects/nms-platform/dash-site-topology.png",
          alt: "NMS site topology page",
          caption: "Topology view for visualizing logical site relationships and device context.",
        },
      ],
    },
    {
      number: 11,
      id: "outcomes",
      label: "Outcomes",
      title: "Outcomes",
      layout: "metrics",
      eyebrow: "11 / 12",
      metrics: [
        { label: "Architecture goal", value: "Distributed monitoring" },
        { label: "Site isolation", value: "Outbound gateway flow" },
        { label: "Preprocessing", value: "Edge/local gateway" },
        { label: "Visibility", value: "Central dashboard" },
      ],
      body: [
        "The project demonstrates a complete monitoring path from local device polling to central visualization, while preserving site isolation and reducing central polling dependency.",
      ],
    },
    {
      number: 12,
      id: "reflection",
      label: "Reflection",
      title: "What I Learned",
      layout: "bullets",
      eyebrow: "12 / 12",
      bullets: [
        "Distributed monitoring reduces WAN polling pressure by moving collection closer to the devices.",
        "Store-and-forward behavior is important for monitoring systems that cross unstable links.",
        "Preprocessing at the gateway makes telemetry more useful before it reaches the central platform.",
        "A BFF layer keeps product UI stable even when the upstream monitoring platform is complex.",
      ],
    },
  ],
};
